---
version: "2.8"

services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - URL=jor.dev
      - VALIDATION=http
      - SUBDOMAINS=www, #optional
      - EMAIL= it@jor.dev
      - ONLY_SUBDOMAINS=false
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - ./config/log:/config/log
      - ./config/nginx/site-confs/default:/config/nginx/site-confs/default
      - ./config/www:/config/www
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks:
      - resume

  resume:
    image: ghcr.io/jorsanders/resume:latest
    container_name: resume
    restart: unless-stopped
    networks:
      - resume

  discord_cage_bot:
    image: ghcr.io/jorsanders/discord_cage_bot:latest
    container_name: discord_cage_bot
    environment:
      - CAGE_BOT_TOKEN
    restart: unless-stopped
    networks:
      - discord_cage_bot

  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./minecraft-data:/data
    networks:
      - minecraft

networks:
  resume: {}
  discord_cage_bot: {}
  minecraft: {}
