---
name: CI-CD

on: [push]

jobs:
  production-deploy:
    if: github.ref == 'refs/heads/main'
    environment: production
    runs-on: ubuntu-latest
    name: Deploy to production server
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to production server and run
        run: |
          echo "===== Creating ~/.ssh directory"
          mkdir -p ~/.ssh/
          echo "$ENVIRONMENT_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo "$ENVIRONMENT_SSH_KEY" > ~/.ssh/ec2_deploy.key
          chmod 600 ~/.ssh/ec2_deploy.key
          echo "===== Starting SSH Agent"
          # shellcheck disable=SC2046
          eval $(ssh-agent -s)
          echo "===== Adding key to agent"
          ssh-add ~/.ssh/ec2_deploy.key
          echo "(Re-)starting Resume"
          ssh "$ENVIRONMENT_USER@$ENVIRONMENT_HOST" 'source ~/.bash_profile && cd ~/Projects/Rpi-setup && git pull && docker compose pull && docker compose up -d'
        shell: bash
        env:
          ENVIRONMENT_HOST: ${{secrets.ENVIRONMENT_HOST}}
          ENVIRONMENT_USER: ${{secrets.ENVIRONMENT_USER}}
          ENVIRONMENT_SSH_KEY: ${{secrets.ENVIRONMENT_SSH_KEY}}
          ENVIRONMENT_SSH_KNOWN_HOSTS: ${{secrets.ENVIRONMENT_SSH_KNOWN_HOSTS}}
